# Mapping Census Data (ACS) - Austin Metropolitan Statistical Area

## Setup

Three required packages are pandas, geopandas, and <a href='https://pypi.org/project/CensusData/'>censusdata</a>

Download these <a href = 'https://drive.google.com/uc?export=download&id=1gW-jxhjfCrRVOHIBJVnaE96VAnCaiC0Q'>SHAPEFILES</a> of the 2010 Census Tracts Unzip them- You only need the .shp

In [ ]:
import pandas as pd, geopandas as gpd, censusdata as cd

 Import your shapefile as a geodataframe

In [80]:
atx_msa_shapes = gpd.read_file(r'C:\Users\benca\Documents\new_jupyter\census_tracts_2010_msa\census_tracts_2010_msa.shp')

Strip off all that weird outdated census data- 
and re-index the data in order of tract

In [81]:
shapes = atx_msa_shapes[['TRACTCE10','geometry']].sort_values('TRACTCE10')
shapes = shapes.reset_index()
shapes = shapes.drop(['index'], axis=1)
sf = shapes['geometry']

In [82]:
shapes

    TRACTCE10                                           geometry
0      000101  POLYGON ((3110996.149 10094866.837, 3111365.29...
1      000102  POLYGON ((3108183.235 10097092.047, 3108282.30...
2      000203  POLYGON ((3117475.629 10088913.117, 3117386.12...
3      000204  POLYGON ((3114760.420 10081981.027, 3114644.63...
4      000205  POLYGON ((3118490.457 10090915.154, 3118437.57...
..        ...                                                ...
345    960400  POLYGON ((3139020.366 9945888.003, 3139114.234...
346    960500  POLYGON ((3093690.406 9947860.118, 3093779.044...
347    960600  POLYGON ((3207292.989 9921228.682, 3208856.500...
348    960700  POLYGON ((3146699.673 9871550.196, 3146926.457...
349    980000  POLYGON ((3136353.703 10054270.459, 3136409.01...

[350 rows x 2 columns]

## Calling the Census API w/ CensusData

Create censusdata.censusgeo objects containing lists of all census tracts by county

In [83]:
atxMetroTracts1 = cd.censusgeo([('state',"48"),('county', '453'),('tract','*')]) # Travis County
atxMetroTracts2 = cd.censusgeo([('state',"48"),('county', '491'),('tract','*')]) # Williamson County
atxMetroTracts3 = cd.censusgeo([('state',"48"),('county', '021'),('tract','*')]) # Bastrop County
atxMetroTracts4 = cd.censusgeo([('state',"48"),('county', '055'),('tract','*')]) # Caldwell County
atxMetroTracts5 = cd.censusgeo([('state',"48"),('county', '209'),('tract','*')]) # Hays County

Let censusdata create your census ACS5 API calls

https://api.census.gov/data/2019/acs/acs5/variables.html

There's like 50K variables in there that you can call using the format below-
the following is race, ethnicity, commute modeshare, and income stratification

In [84]:
## df = censusdata.download(Survey_type, Year, Geographies, ['variable','variable2', ...])
temp1 = cd.download('acs5', 2019, atxMetroTracts1, ['B02001_001E', 'B02001_002E', 'B02001_003E', 'B02001_004E', 'B02001_005E', 'B02001_006E', 'B02001_007E', 'B02001_008E', 'B02001_009E', 'B02001_010E', 'B03003_002E', 'B03003_003E', 'B08006_001E', 'B08006_002E', 'B08006_003E', 'B08006_004E', 'B08006_005E', 'B08006_006E', 'B08006_007E', 'B08006_008E', 'B08006_009E', 'B08006_010E', 'B08006_011E', 'B08006_012E', 'B08006_013E', 'B08006_014E', 'B08006_015E', 'B08006_016E', 'B08006_017E','B08119_001E', 'B08119_002E', 'B08119_003E', 'B08119_004E', 'B08119_005E', 'B08119_006E', 'B08119_007E', 'B08119_008E', 'B08119_009E'])
temp2 = cd.download('acs5', 2019, atxMetroTracts2, ['B02001_001E', 'B02001_002E', 'B02001_003E', 'B02001_004E', 'B02001_005E', 'B02001_006E', 'B02001_007E', 'B02001_008E', 'B02001_009E', 'B02001_010E', 'B03003_002E', 'B03003_003E', 'B08006_001E', 'B08006_002E', 'B08006_003E', 'B08006_004E', 'B08006_005E', 'B08006_006E', 'B08006_007E', 'B08006_008E', 'B08006_009E', 'B08006_010E', 'B08006_011E', 'B08006_012E', 'B08006_013E', 'B08006_014E', 'B08006_015E', 'B08006_016E', 'B08006_017E','B08119_001E', 'B08119_002E', 'B08119_003E', 'B08119_004E', 'B08119_005E', 'B08119_006E', 'B08119_007E', 'B08119_008E', 'B08119_009E'])
temp3 = cd.download('acs5', 2019, atxMetroTracts3, ['B02001_001E', 'B02001_002E', 'B02001_003E', 'B02001_004E', 'B02001_005E', 'B02001_006E', 'B02001_007E', 'B02001_008E', 'B02001_009E', 'B02001_010E', 'B03003_002E', 'B03003_003E', 'B08006_001E', 'B08006_002E', 'B08006_003E', 'B08006_004E', 'B08006_005E', 'B08006_006E', 'B08006_007E', 'B08006_008E', 'B08006_009E', 'B08006_010E', 'B08006_011E', 'B08006_012E', 'B08006_013E', 'B08006_014E', 'B08006_015E', 'B08006_016E', 'B08006_017E','B08119_001E', 'B08119_002E', 'B08119_003E', 'B08119_004E', 'B08119_005E', 'B08119_006E', 'B08119_007E', 'B08119_008E', 'B08119_009E'])
temp4 = cd.download('acs5', 2019, atxMetroTracts4, ['B02001_001E', 'B02001_002E', 'B02001_003E', 'B02001_004E', 'B02001_005E', 'B02001_006E', 'B02001_007E', 'B02001_008E', 'B02001_009E', 'B02001_010E', 'B03003_002E', 'B03003_003E', 'B08006_001E', 'B08006_002E', 'B08006_003E', 'B08006_004E', 'B08006_005E', 'B08006_006E', 'B08006_007E', 'B08006_008E', 'B08006_009E', 'B08006_010E', 'B08006_011E', 'B08006_012E', 'B08006_013E', 'B08006_014E', 'B08006_015E', 'B08006_016E', 'B08006_017E','B08119_001E', 'B08119_002E', 'B08119_003E', 'B08119_004E', 'B08119_005E', 'B08119_006E', 'B08119_007E', 'B08119_008E', 'B08119_009E'])
temp5 = cd.download('acs5', 2019, atxMetroTracts5, ['B02001_001E', 'B02001_002E', 'B02001_003E', 'B02001_004E', 'B02001_005E', 'B02001_006E', 'B02001_007E', 'B02001_008E', 'B02001_009E', 'B02001_010E', 'B03003_002E', 'B03003_003E', 'B08006_001E', 'B08006_002E', 'B08006_003E', 'B08006_004E', 'B08006_005E', 'B08006_006E', 'B08006_007E', 'B08006_008E', 'B08006_009E', 'B08006_010E', 'B08006_011E', 'B08006_012E', 'B08006_013E', 'B08006_014E', 'B08006_015E', 'B08006_016E', 'B08006_017E','B08119_001E', 'B08119_002E', 'B08119_003E', 'B08119_004E', 'B08119_005E', 'B08119_006E', 'B08119_007E', 'B08119_008E', 'B08119_009E'])

SLAP it together

In [86]:
atx_msa_demo = temp1.append(temp2.append(temp3.append(temp4.append(temp5))))
atx_msa_demo

,B02001_001E,B02001_002E,B02001_003E,B02001_004E,B02001_005E,B02001_006E,B02001_007E,B02001_008E,B02001_009E,B02001_010E,...,B08006_017E,B08119_001E,B08119_002E,B08119_003E,B08119_004E,B08119_005E,B08119_006E,B08119_007E,B08119_008E,B08119_009E
"Census Tract 21.10, Travis County, Texas: Summary level: 140, state:48> county:453> tract:002110",4221,1523,1348,11,48,0,1205,86,16,70,...,123,2287,181,160,564,426,425,160,74,297
"Census Tract 23.15, Travis County, Texas: Summary level: 140, state:48> county:453> tract:002315",2954,2190,191,0,56,0,447,70,0,70,...,58,2131,131,202,430,587,352,261,23,145
"Census Tract 18.35, Travis County, Texas: Summary level: 140, state:48> county:453> tract:001835",6771,4190,1434,0,571,0,293,283,145,138,...,197,3700,463,202,486,619,622,750,219,339
"Census Tract 18.40, Travis County, Texas: Summary level: 140, state:48> county:453> tract:001840",10880,6828,2062,0,910,0,636,444,172,272,...,257,6054,545,351,774,1240,926,770,325,1123
"Census Tract 18.50, Travis County, Texas: Summary level: 140, state:48> county:453> tract:001850",3782,3042,327,15,317,0,38,43,0,43,...,184,2507,125,157,267,296,474,395,277,516
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
"Census Tract 109.10, Hays County, Texas: Summary level: 140, state:48> county:209> tract:010910",10379,9059,705,22,29,0,303,261,38,223,...,223,5295,357,311,832,893,952,987,204,759
"Census Tract 103.03, Hays County, Texas: Summary level: 140, state:48> county:209> tract:010303",9097,7108,1314,13,49,20,315,278,92,186,...,131,5274,1430,502,847,1061,803,356,214,61
"Census Tract 103.04, Hays County, Texas: Summary level: 140, state:48> county:209> tract:010304",7923,6816,601,21,9,0,282,194,72,122,...,68,4103,1186,554,916,496,639,167,20,125
"Census Tract 107.01, Hays County, Texas: Summary level: 140, state:48> county:209> tract:010701",8677,7905,124,31,476,0,93,48,19,29,...,255,5327,993,747,1517,796,336,297,179,462
"Census Tract 107.02, Hays County, Texas: Summary level: 140, state:48> county:209> tract:010702",2893,2653,105,18,11,0,100,6,0,6,...,61,1424,259,240,219,239,212,86,37,132

## Cleaning our Results

Right now, our index is a censusdata.censusgeo object that looks like this

In [87]:
atx_msa_demo.index[0]

censusgeo((('state', '48'), ('county', '453'), ('tract', '002110')), 'Census Tract 21.10, Travis County, Texas')

In [88]:
## EXTRACT THE TRACT AND COUNTY INTO THEIR OWN COLUMNS

atx_msa_demo['tract']=0
for x in range(350):
    atx_msa_demo['tract'][x] = atx_msa_demo.index[x].geo[2][1]
    
atx_msa_demo['county'] = 0
for x in range(350):
    atx_msa_demo['county'][x] = atx_msa_demo.index[x].geo[1][1]
    
## CREATE A NEW INDEX ORDERED BY TRACT NUMBER 

atx_msa_demo = atx_msa_demo.sort_values(by=['tract'])    
atx_msa_demo = atx_msa_demo.reset_index()

## DROP THE OLD INDEX (censusdata.censusgeo)

atx_msa_demo = atx_msa_demo.drop(['index'], axis=1)

## Now our data and our shapefiles share the same index in order of tract

In [89]:
atx_msa_demo

,B02001_001E,B02001_002E,B02001_003E,B02001_004E,B02001_005E,B02001_006E,B02001_007E,B02001_008E,B02001_009E,B02001_010E,...,B08119_002E,B08119_003E,B08119_004E,B08119_005E,B08119_006E,B08119_007E,B08119_008E,B08119_009E,tract,county
0,4411,4014,11,17,95,0,76,198,49,149,...,183,76,259,145,164,341,164,1200,101,453
1,2580,2446,15,0,73,0,2,44,0,44,...,64,70,91,42,77,63,62,756,102,453
2,2334,1756,239,11,224,33,33,38,0,38,...,312,20,81,65,156,171,81,315,203,453
3,3096,2630,60,0,179,0,26,201,23,178,...,133,138,139,138,122,264,93,653,204,453
4,3930,3266,99,12,272,0,120,161,0,161,...,74,114,289,392,572,631,279,871,205,453
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
345,3723,3020,353,19,15,0,254,62,0,62,...,222,181,283,391,429,277,31,123,960400,55
346,7676,6417,670,4,0,6,483,96,3,93,...,574,390,892,527,499,274,144,373,960500,55
347,2495,2328,28,0,0,0,103,36,0,36,...,96,58,142,166,177,181,35,351,960600,55
348,6058,4158,482,0,23,47,1268,80,18,62,...,123,297,680,498,250,253,179,295,960700,55
349,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,980000,453

In [90]:
shapes

    TRACTCE10                                           geometry
0      000101  POLYGON ((3110996.149 10094866.837, 3111365.29...
1      000102  POLYGON ((3108183.235 10097092.047, 3108282.30...
2      000203  POLYGON ((3117475.629 10088913.117, 3117386.12...
3      000204  POLYGON ((3114760.420 10081981.027, 3114644.63...
4      000205  POLYGON ((3118490.457 10090915.154, 3118437.57...
..        ...                                                ...
345    960400  POLYGON ((3139020.366 9945888.003, 3139114.234...
346    960500  POLYGON ((3093690.406 9947860.118, 3093779.044...
347    960600  POLYGON ((3207292.989 9921228.682, 3208856.500...
348    960700  POLYGON ((3146699.673 9871550.196, 3146926.457...
349    980000  POLYGON ((3136353.703 10054270.459, 3136409.01...

[350 rows x 2 columns]

### I'm going to do some calculations now before I combine the data with the shapes

In [94]:
## Adding sq feet to each tract without actually linking the geometries yet- 
## Just calculating area from the geometry, and adding a column to our census data

atx_msa_demo['sqft'] = 0.0000001
for x in range(350):
    atx_msa_demo['sqft'][x] = sf[x].area
    
## Population Density

atx_msa_demo['pop_density'] = (atx_msa_demo['B02001_001E']*5280*5280)/atx_msa_demo['sqft']
    
## Race / Ethnicity

atx_msa_demo['percent_white'] = atx_msa_demo['B02001_002E']/atx_msa_demo['B02001_001E']
atx_msa_demo['percent_black'] = atx_msa_demo['B02001_003E']/atx_msa_demo['B02001_001E']
atx_msa_demo['percent_native'] = atx_msa_demo['B02001_004E']/atx_msa_demo['B02001_001E']
atx_msa_demo['percent_asian'] = atx_msa_demo['B02001_005E']/atx_msa_demo['B02001_001E']
atx_msa_demo['percent_hpi'] = atx_msa_demo['B02001_006E']/atx_msa_demo['B02001_001E']
atx_msa_demo['percent_other_race'] = atx_msa_demo['B02001_007E']/atx_msa_demo['B02001_001E']
atx_msa_demo['percent_multi_race'] = atx_msa_demo['B02001_008E']/atx_msa_demo['B02001_001E']

atx_msa_demo['white_density'] = (atx_msa_demo['B02001_002E'] * 5280 * 5280) / atx_msa_demo['sqft']
atx_msa_demo['black_density'] = (atx_msa_demo['B02001_003E'] * 5280 * 5280) / atx_msa_demo['sqft']
atx_msa_demo['native_density'] = (atx_msa_demo['B02001_004E'] * 5280 * 5280) / atx_msa_demo['sqft']
atx_msa_demo['asian_density'] = (atx_msa_demo['B02001_005E'] * 5280 * 5280) / atx_msa_demo['sqft']
atx_msa_demo['hpi_density'] = (atx_msa_demo['B02001_006E'] * 5280 * 5280) / atx_msa_demo['sqft']
atx_msa_demo['other_race_density'] = (atx_msa_demo['B02001_007E'] * 5280 * 5280) / atx_msa_demo['sqft']
atx_msa_demo['multi_race_density'] = (atx_msa_demo['B02001_008E'] * 5280 * 5280) / atx_msa_demo['sqft']

atx_msa_demo['percent_latino'] = atx_msa_demo['B03003_003E']/atx_msa_demo['B02001_001E']
atx_msa_demo['latino_density'] = (atx_msa_demo['B03003_003E'] * 5280 * 5280) / atx_msa_demo['sqft']

## Transportation

atx_msa_demo['percent_drove_alone'] = atx_msa_demo['B08006_003E'] / atx_msa_demo['B08006_001E']
atx_msa_demo['percent_carpool'] = atx_msa_demo['B08006_004E'] / atx_msa_demo['B08006_001E']
atx_msa_demo['percent_transit'] = atx_msa_demo['B08006_008E'] / atx_msa_demo['B08006_001E']
atx_msa_demo['percent_biked'] = atx_msa_demo['B08006_014E'] / atx_msa_demo['B08006_001E']
atx_msa_demo['percent_walked'] = atx_msa_demo['B08006_015E'] / atx_msa_demo['B08006_001E']
atx_msa_demo['percent_taxi_moto'] = atx_msa_demo['B08006_016E'] / atx_msa_demo['B08006_001E']
atx_msa_demo['percent_wfh'] = atx_msa_demo['B08006_017E'] / atx_msa_demo['B08006_001E']

atx_msa_demo['drove_alone_density'] = (atx_msa_demo['B08006_003E'] * 5280 * 5280) / atx_msa_demo['sqft']
atx_msa_demo['carpool_density'] = (atx_msa_demo['B08006_004E'] * 5280 * 5280) / atx_msa_demo['sqft']
atx_msa_demo['transit_density'] = (atx_msa_demo['B08006_008E'] * 5280 * 5280) / atx_msa_demo['sqft']
atx_msa_demo['bike_density'] = (atx_msa_demo['B08006_014E'] * 5280 * 5280) / atx_msa_demo['sqft']
atx_msa_demo['walk_density'] = (atx_msa_demo['B08006_015E'] * 5280 * 5280) / atx_msa_demo['sqft']
atx_msa_demo['taxi_moto_density'] = (atx_msa_demo['B08006_016E'] * 5280 * 5280) / atx_msa_demo['sqft']
atx_msa_demo['wfh_density'] = (atx_msa_demo['B08006_017E'] * 5280 * 5280) / atx_msa_demo['sqft']

atx_msa_demo['percent_active_modeshare'] = (atx_msa_demo['B08006_014E'] + atx_msa_demo['B08006_015E'] + atx_msa_demo['B08006_008E']) / atx_msa_demo['B08006_001E']
atx_msa_demo['active_mode_density'] = ((atx_msa_demo['B08006_014E'] + atx_msa_demo['B08006_015E'] + atx_msa_demo['B08006_008E'])*5280*5280) / atx_msa_demo['sqft']

atx_msa_demo['active_minus_carpool'] = (atx_msa_demo['B08006_014E'] + atx_msa_demo['B08006_015E'] + atx_msa_demo['B08006_008E']-atx_msa_demo['B08006_004E'])/atx_msa_demo['B08006_001E']
atx_msa_demo['active_minus_carpool_density'] = ((atx_msa_demo['B08006_014E'] + atx_msa_demo['B08006_015E'] + atx_msa_demo['B08006_008E']-atx_msa_demo['B08006_004E'])*5280*5280) / atx_msa_demo['sqft']
## Income

atx_msa_demo['percent_under_25K'] = (atx_msa_demo['B08119_002E'] + atx_msa_demo['B08119_003E'] + atx_msa_demo['B08119_004E']) / atx_msa_demo['B08119_001E']
atx_msa_demo['percent_25K_50K'] = (atx_msa_demo['B08119_005E'] + atx_msa_demo['B08119_006E']) / atx_msa_demo['B08119_001E']
atx_msa_demo['percent_50K_75K'] = (atx_msa_demo['B08119_007E'] + atx_msa_demo['B08119_008E']) / atx_msa_demo['B08119_001E']
atx_msa_demo['percent_75K_plus'] = atx_msa_demo['B08119_009E'] / atx_msa_demo['B08119_001E']

atx_msa_demo['density_under_25K'] = ((atx_msa_demo['B08119_002E'] + atx_msa_demo['B08119_003E'] + atx_msa_demo['B08119_004E'])*5280*5280)/atx_msa_demo['sqft']
atx_msa_demo['density_25K_50K'] = ((atx_msa_demo['B08119_005E'] + atx_msa_demo['B08119_006E'])*5280*5280)/atx_msa_demo['sqft']
atx_msa_demo['density_50K_75K'] = ((atx_msa_demo['B08119_007E'] + atx_msa_demo['B08119_008E'])*5280*5280)/atx_msa_demo['sqft']
atx_msa_demo['density_75K_plus'] = (atx_msa_demo['B08119_009E']*5280*5280)/atx_msa_demo['sqft']

<ipython-input-94-3f4be18423d7>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  atx_msa_demo['sqft'][x] = sf[x].area

## Combining Data and Shapefiles

In [102]:
export = gpd.GeoDataFrame(
    atx_msa_demo, geometry=sf)
export

,B02001_001E,B02001_002E,B02001_003E,B02001_004E,B02001_005E,B02001_006E,B02001_007E,B02001_008E,B02001_009E,B02001_010E,...,percent_50K_75K,percent_75K_plus,density_under_25K,density_25K_50K,density_50K_75K,density_75K_plus,pop_density,geometry,active_minus_carpool,active_minus_carpool_density
0,4411,4014,11,17,95,0,76,198,49,149,...,0.199447,0.473934,429.129488,255.986509,418.359829,994.122366,3654.228132,"POLYGON ((3110996.149 10094866.837, 3111365.29...",0.033965,71.245436
1,2580,2446,15,0,73,0,2,44,0,44,...,0.102041,0.617143,103.379748,54.676400,57.433193,347.355953,1185.421109,"POLYGON ((3108183.235 10097092.047, 3108282.30...",-0.001633,-0.918931
2,2334,1756,239,11,224,33,33,38,0,38,...,0.209825,0.262281,884.545293,473.328111,539.722552,674.653190,4998.858873,"POLYGON ((3117475.629 10088913.117, 3117386.12...",0.168193,432.634744
3,3096,2630,60,0,179,0,26,201,23,178,...,0.212500,0.388690,581.945563,369.038650,506.718453,926.854762,4394.398689,"POLYGON ((3114760.420 10081981.027, 3114644.63...",0.135119,322.199129
4,3930,3266,99,12,272,0,120,161,0,161,...,0.282433,0.270329,819.193109,1655.560079,1562.821236,1495.843183,6749.326877,"POLYGON ((3118490.457 10090915.154, 3118437.57...",0.170701,944.562286
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
345,3723,3020,353,19,15,0,254,62,0,62,...,0.159009,0.063500,74.104149,88.579303,33.271250,13.286895,402.171640,"POLYGON ((3139020.366 9945888.003, 3139114.234...",-0.145070,-30.354615
346,7676,6417,670,4,0,6,483,96,3,93,...,0.113803,0.101552,20.601980,11.388810,4.639885,4.140376,85.205170,"POLYGON ((3093690.406 9947860.118, 3093779.044...",0.071331,2.908254
347,2495,2328,28,0,0,0,103,36,0,36,...,0.179104,0.291045,1.551795,1.798195,1.132391,1.840136,13.080168,"POLYGON ((3207292.989 9921228.682, 3208856.500...",-0.094059,-0.597651
348,6058,4158,482,0,23,47,1268,80,18,62,...,0.167767,0.114563,82.233145,55.918539,32.295199,22.053434,452.880356,"POLYGON ((3146699.673 9871550.196, 3146926.457...",-0.128544,-24.744701
349,0,0,0,0,0,0,0,0,0,0,...,NaN,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,"POLYGON ((3136353.703 10054270.459, 3136409.01...",NaN,0.000000

## Write to a shapefile

In [103]:
export.to_file("atx_msa_demographic.shp")

## I took these new shapefiles into tableau

In [7]:
%%html
<div class='tableauPlaceholder' id='viz1611873395341' style='position: relative'><noscript><a href='#'><img alt=' ' src='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;TS&#47;TSZZ95RP3&#47;1_rss.png' style='border: none' /></a></noscript><object class='tableauViz'  style='display:none;'><param name='host_url' value='https%3A%2F%2Fpublic.tableau.com%2F' /> <param name='embed_code_version' value='3' /> <param name='path' value='shared&#47;TSZZ95RP3' /> <param name='toolbar' value='yes' /><param name='static_image' value='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;TS&#47;TSZZ95RP3&#47;1.png' /> <param name='animate_transition' value='yes' /><param name='display_static_image' value='yes' /><param name='display_spinner' value='yes' /><param name='display_overlay' value='yes' /><param name='display_count' value='yes' /><param name='language' value='en' /><param name='filter' value='publish=yes' /></object></div>                <script type='text/javascript'>                    var divElement = document.getElementById('viz1611873395341');                    var vizElement = divElement.getElementsByTagName('object')[0];                    vizElement.style.width='100%';vizElement.style.height=(divElement.offsetWidth*0.75)+'px';                    var scriptElement = document.createElement('script');                    scriptElement.src = 'https://public.tableau.com/javascripts/api/viz_v1.js';                    vizElement.parentNode.insertBefore(scriptElement, vizElement);                </script>

In [13]:
%%html
<div class='tableauPlaceholder' id='viz1611932583217' style='position: relative'><noscript><a href='#'><img alt=' ' src='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;bl&#47;blacklatinoPopulationDensity&#47;blacklatinodens&#47;1_rss.png' style='border: none' /></a></noscript><object class='tableauViz'  style='display:none;'><param name='host_url' value='https%3A%2F%2Fpublic.tableau.com%2F' /> <param name='embed_code_version' value='3' /> <param name='site_root' value='' /><param name='name' value='blacklatinoPopulationDensity&#47;blacklatinodens' /><param name='tabs' value='no' /><param name='toolbar' value='yes' /><param name='static_image' value='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;bl&#47;blacklatinoPopulationDensity&#47;blacklatinodens&#47;1.png' /> <param name='animate_transition' value='yes' /><param name='display_static_image' value='yes' /><param name='display_spinner' value='yes' /><param name='display_overlay' value='yes' /><param name='display_count' value='yes' /><param name='language' value='en' /><param name='filter' value='publish=yes' /></object></div>                <script type='text/javascript'>                    var divElement = document.getElementById('viz1611932583217');                    var vizElement = divElement.getElementsByTagName('object')[0];                    if ( divElement.offsetWidth > 800 ) { vizElement.style.width='100%';vizElement.style.height=(divElement.offsetWidth*0.75)+'px';} else if ( divElement.offsetWidth > 500 ) { vizElement.style.width='100%';vizElement.style.height=(divElement.offsetWidth*0.75)+'px';} else { vizElement.style.width='100%';vizElement.style.height='727px';}                     var scriptElement = document.createElement('script');                    scriptElement.src = 'https://public.tableau.com/javascripts/api/viz_v1.js';                    vizElement.parentNode.insertBefore(scriptElement, vizElement);                </script>

In [14]:
%%html
<div class='tableauPlaceholder' id='viz1611933828535' style='position: relative'><noscript><a href='#'><img alt=' ' src='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;tr&#47;transitdensityandmodeshare&#47;Sheet8&#47;1_rss.png' style='border: none' /></a></noscript><object class='tableauViz'  style='display:none;'><param name='host_url' value='https%3A%2F%2Fpublic.tableau.com%2F' /> <param name='embed_code_version' value='3' /> <param name='site_root' value='' /><param name='name' value='transitdensityandmodeshare&#47;Sheet8' /><param name='tabs' value='no' /><param name='toolbar' value='yes' /><param name='static_image' value='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;tr&#47;transitdensityandmodeshare&#47;Sheet8&#47;1.png' /> <param name='animate_transition' value='yes' /><param name='display_static_image' value='yes' /><param name='display_spinner' value='yes' /><param name='display_overlay' value='yes' /><param name='display_count' value='yes' /><param name='language' value='en' /><param name='filter' value='publish=yes' /></object></div>                <script type='text/javascript'>                    var divElement = document.getElementById('viz1611933828535');                    var vizElement = divElement.getElementsByTagName('object')[0];                    vizElement.style.width='100%';vizElement.style.height=(divElement.offsetWidth*0.75)+'px';                    var scriptElement = document.createElement('script');                    scriptElement.src = 'https://public.tableau.com/javascripts/api/viz_v1.js';                    vizElement.parentNode.insertBefore(scriptElement, vizElement);                </script>

In [24]:
%%html
<div class='tableauPlaceholder' id='viz1611969958845' style='position: relative'><noscript><a href='#'><img alt=' ' src='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;Cy&#47;Cyclistmodeshareanddensity&#47;Dashboard3&#47;1_rss.png' style='border: none' /></a></noscript><object class='tableauViz'  style='display:none;'><param name='host_url' value='https%3A%2F%2Fpublic.tableau.com%2F' /> <param name='embed_code_version' value='3' /> <param name='site_root' value='' /><param name='name' value='Cyclistmodeshareanddensity&#47;Dashboard3' /><param name='tabs' value='no' /><param name='toolbar' value='yes' /><param name='static_image' value='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;Cy&#47;Cyclistmodeshareanddensity&#47;Dashboard3&#47;1.png' /> <param name='animate_transition' value='yes' /><param name='display_static_image' value='yes' /><param name='display_spinner' value='yes' /><param name='display_overlay' value='yes' /><param name='display_count' value='yes' /><param name='language' value='en' /><param name='filter' value='publish=yes' /></object></div>                <script type='text/javascript'>                    var divElement = document.getElementById('viz1611969958845');                    var vizElement = divElement.getElementsByTagName('object')[0];                    vizElement.style.minWidth='420px';vizElement.style.maxWidth='1020px';vizElement.style.width='100%';vizElement.style.minHeight='587px';vizElement.style.maxHeight='687px';vizElement.style.height=(divElement.offsetWidth*0.75)+'px';                    var scriptElement = document.createElement('script');                    scriptElement.src = 'https://public.tableau.com/javascripts/api/viz_v1.js';                    vizElement.parentNode.insertBefore(scriptElement, vizElement);                </script>